apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the branch for the git repo
    - name: url
      description: pr's url
    - name: SOAR_URL
      description: soar env
    - name: API_SECRET
      description: secret
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: params-resilient-task
      taskRef:
        name: call-resilient
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: url
          value: $(params.url)
        - name: SOAR_URL
          value: $(params.SOAR_URL)
        - name: API_SECRET
          value: $(params.API_SECRET)
    - name: call-resilient
      runAfter: [params-resilient-task]
      taskRef:
        name: curl
      params:
        - name: url
          value: $(params.SOAR_URL)
        - name: options
          value:
            - "-basic -u $(params.API_SECRET)"
      
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc          

