apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the branch for the git repo
    - name: url
      description: pr's url
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: call-resilient-task
      taskRef:
        name: call-resilient
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: url
          value: $(params.url)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc          

