apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the branch for the git repo
    - name: url
      description: pr's url
    - name: SOAR_URL
      description: soar env
    - name: API_SECRET
      description: secret
    - name: API_KEY_ID
      description: apikey
    - name: HEADER_TEXT
      description: text in incident
    - name: ORG
      description: org id
    - name: compliance_change
      description: compliance change repo's url
    - name: evidence_repo
      description: evidence repo's url
    - name: incident_repo
      description: incident repo's url
    - name: inventory_repo
      description: inventory repo's url
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: call-resilient-task
      taskRef:
        name: call-resilient
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: url
          value: $(params.url)
        - name: SOAR_URL
          value: $(params.SOAR_URL)
        - name: API_SECRET
          value: $(params.API_SECRET)
        - name: API_KEY_ID
          value: $(params.API_KEY_ID)
        - name: ORG
          value: $(params.ORG)
        - name: HEADER_TEXT
          value: $(params.HEADER_TEXT)
        - name: compliance_change
          value: $(params.compliance_change)
        - name: evidence_repo
          value: $(params.evidence_repo)
        - name: incident_repo
          value: $(params.incident_repo)
        - name: inventory_repo
          value: $(params.inventory_repo)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc          

