apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: call-resilient
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the revision
      default: master
    - name: url
      description: pr's url
    - name: SOAR_URL
      description: soar env
    - name: API_SECRET
      description: secret
  workspaces:
    - name: task-pvc
      mountPath: /artifacts
  steps:
    - name: resilient-api
      image: ibmcom/pipeline-base-image
      env:
        - name: GIT_URL
          value: $(params.repository)
        - name: PR_URL
          value: $(params.url)
        - name: REVISION
          value: $(params.revision)
        - name: SOAR_URL
          value: $(params.SOAR_URL)
        - name: API_SECRET
          value: $(params.API_SECRET)
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          echo $PR_URL;
          echo $SOAR_URL;

  # sidecars:
  #   - image: moby/buildkit:v0.8.1
  #     name: server
  #     securityContext:
  #       privileged: true
  #       # Use a workaround to by pass virtio-fs for Continuous Delivery shared workers
  #     command: ["sh", "-c"]
  #     args:
  #       - if [[ $(df -PT /var/lib/buildkit | awk 'NR==2 {print $2}') == virtiofs ]]; then
  #          apk add e2fsprogs &&
  #          truncate -s 20G /tmp/disk.img &&
  #          mkfs.ext4 /tmp/disk.img &&
  #          mount /tmp/disk.img /var/lib/buildkit; fi && buildkitd --addr tcp://0.0.0.0:1234;
  #     # Wait for the buildkit daemon to have available workers.
  #     readinessProbe:
  #       initialDelaySeconds: 2
  #       periodSeconds: 1
  #       exec:
  #         command: ["buildctl", "--addr", "tcp://0.0.0.0:1234", "debug", "workers"]
