apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: call-resilient
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the revision
      default: master
    - name: url
      description: pr's url
    - name: SOAR_URL
      description: soar env
    - name: API_SECRET
      description: secret
    - name: API_KEY_ID
      description: apikey
    - name: ORG
      description: org incident
    - name: HEADER_TEXT
      description: name of incident
    - name: compliance_change
      description: compliance change repo's url
    - name: evidence_repo
      description: evidence repo's url
    - name: incident_repo
      description: incident repo's url
    - name: inventory_repo
      description: inventory repo's url
  workspaces:
    - name: task-pvc
      mountPath: /artifacts
  steps:
    - name: resilient-api
      image: ibmcom/pipeline-base-image
      env:
        - name: GIT_URL
          value: $(params.repository)
        - name: PR_URL
          value: $(params.url)
        - name: REVISION
          value: $(params.revision)
        - name: SOAR_URL
          value: $(params.SOAR_URL)
        - name: API_SECRET
          value: $(params.API_SECRET)
        - name: API_KEY_ID
          value: $(params.API_KEY_ID)
        - name: ORG
          value: $(params.ORG)
        - name: HEADER_TEXT
          value: $(params.HEADER_TEXT)
        - name: compliance_change
          value: $(params.compliance_change)
        - name: evidence_repo
          value: $(params.evidence_repo)
        - name: incident_repo
          value: $(params.incident_repo)
        - name: inventory_repo
          value: $(params.inventory_repo)
      script: |
        #!/usr/bin/env bash
        set -xe
        echo $PR_URL
        echo $SOAR_URL
        curl -basic -u $API_KEY_ID:$API_SECRET -k "${SOAR_URL}/rest/orgs/${ORG}/incidents?want_full_data=false&want_tasks=false" -X POST  -H 'Content-Type: application/json' -H 'Accept-Language: en-US,en;q=0.9' -H 'Accept: */*'  -H 'Connection: keep-alive' --data-raw "{\"name\": \"${HEADER_TEXT}\",\"discovered_date\": $(date +%s000),\"description\":{\"format\":\"html\",  \"content\": \"<div><a href='${GIT_URL}' >GITHUB PULL REQUEST</a></div><div><a href='${compliance_change}' >COMPLIANCE CHANGE</a></div><div><a href='${evidence_repo}' >EVIDENCE REPO</a></div><div><a href='${incident_repo}' >INCIDENT REPO</a></div><div><a href='${inventory_repo}' >INVENTORY REPO</a></div>\"},\"perms\": { \"create_artifacts\": true},\"artifacts\": [{ \"type\": {\"name\": \"URL\" }, \"value\": \"${GIT_URL}\"}, { \"type\": {\"name\": \"URL\" }, \"value\": \"${compliance_change}\"}, { \"type\": {\"name\": \"URL\" }, \"value\": \"${evidence_repo}\"}, { \"type\": {\"name\": \"URL\" }, \"value\": \"${incident_repo}\"}, { \"type\": {\"name\": \"URL\" }, \"value\": \"${inventory_repo}\"}]}"

      # command: ["/bin/bash", "-c"]
      # args:
      #   - set -e -o pipefail;
      #     echo $PR_URL;
      #     echo $SOAR_URL;
         # curl -basic -u bf03a91f-bf89-4559-b805-fc3716cd7f0f:dnhUdBqPm-BL7Xhw7JPzrodhOfioASFgE4EaaegOoV0 -k 'https://soar.cp4s.com.pl/rest/orgs/201/incidents?want_full_data=false&want_tasks=false' -X POST  -H 'Content-Type: application/json' -H 'Accept-Language: en-US,en;q=0.9' -H 'Accept: */*'  -H 'Connection: keep-alive' --data-raw "{\"name\": \"TEST\",\"discovered_date\": 12345,\"perms\": { \"create_artifacts\": true},\"artifacts\": [{ \"type\": {\"name\": \"URL\" }, \"value\": \"https://github.com\"}]}";


 